version: '3.5'
services:

    mysql:
        image: mysql:5.7
        restart: on-failure
        env_file:
            - .env
        ports:
            - 3306:${MYSQL_PORT}
        volumes:
            - "./db/database.sql:/docker-entrypoint-initdb.d/database.sql"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8080:80
        links:
            - "mysql:db"
        environment:
            - "PMA_HOST:db"

    october-app:
        build: .
        ports:
            - "80:80"
        volumes:
            - ./:/usr/share/nginx/html
            - .docker/nginx.conf:/etc/nginx/conf.d/default.conf
